### ISSUE TITLE
Integrate Material-ui 

### ISSUE THREAD

**Issue by KhalilZaidoun** [unimonkiez/react-cordova-boilerplate#10]
Hi, thx for sharing this boilerplate. can anyone write ana implementation with material-ui or react-bootstrap ?

**Comment by unimonkiez** [comment]
I saw someone that started using material ui in one of the forks ([here](https://github.com/aaronduchateau/react-cordova-boilerplate)).

Other than that you can check material ui docs, I've used it in another project of mine, works mostly fine.
