### ISSUE TITLE
How ToDoApp gets the todos

### ISSUE THREAD

**Issue by khayalan-mathew** [unimonkiez/react-cordova-boilerplate#14]
Hey dear community :)

I need a little bit of help:
The ToDoApp takes as prop todos (i guess from store).
But i dont find from where it gets this prop?

Any help?

**Comment by omerman** [comment]
Take a look at the reducers/index.js,
```
export default combineReducers({
  todos,
  credentials
});
```
as you can see, a "todos" reducer is declared.
This reducer also writes a default array value to the state and mainly after every change,
this reducer will produce an array state. ( as you can see under reducers/todos.js)

If you now take a look under containers/ToDoApp.jsx,
```
export default connect(state => ({ todos: state.todos }), dispatch => ({
  credentialsActions: bindActionCreators(CredentialsActions, dispatch),
  todoActions: bindActionCreators(TodoActions, dispatch)
}))(TodoApp);
```
you'll see that the todos prop is taken(injected via the connect method) from `state.todos`.

**Comment by khayalan-mathew** [comment]
Thanks :)
