### ISSUE TITLE
How to integrate React-Big-Calendar

### ISSUE THREAD

**Issue by khayalan-mathew** [unimonkiez/react-cordova-boilerplate#17]
Hey dear Community,

everyday i get a little forward with my app ^^ Today i want to add the Calendar and found react-big-calendar (a FullCalendar synonym for React). I installed it properly and added it to the Calendar-Page.

One thing i didnt managed to do is to give it the appropiate style ^^

In normal cases i can use like  TESTCSS[testclass] to give the object the corresponding css.
But since this is a Package i dont managed to do it. 

Here is the Container, where i build the Calendar ([LINK](https://github.com/khayalan-mathew/gymdonapp/blob/feature/react-redux/src/containers/PageCalendar.jsx))

Thanks for any help in advance

**Comment by khayalan-mathew** [comment]
My question is:  How i add a css-file globally so the module uses it

**Comment by unimonkiez** [comment]
Can't you just import it?
* scss
```scss
@include('~react-big-calendar/lib/css/react-big-calendar.css');
```
* js
```es6
import 'react-big-calendar/lib/css/react-big-calendar.css';
```

**Comment by khayalan-mathew** [comment]
Tried it but since every cssclass gets a hashtag they dont get applied correctly...
Fixed it by making a new file  ([>CLICK<](https://github.com/khayalan-mathew/gymdonapp/blob/feature/react-redux/src/style/calendar.css))
And then applying the calendarStyle Class to the Calendar .

Fixed it

**Comment by unimonkiez** [comment]
Actually loading css files from `node_modules` directory should not modulize the class name..  
you can add that exception easily to the webpack config file 👍

**Comment by unimonkiez** [comment]
The new version now won't modulize css files by default, feel free to try it 😸
