### ISSUE TITLE
how to use images with the boilerplate?

### ISSUE THREAD

**Issue by iliran11** [unimonkiez/react-cordova-boilerplate#26]
hi,
i am putting a png file inside: '/resources' and referencing the file in this way:

```jsx
<img style={titlebarImage} src='resources/device-titlebar.jpg'/>
```
while running `npm start` and check it in the web, using chrome, it runs OK.
while running:

```
npm run build
cordova run android
```

app loads to the android studio emulator, but images are not loaded.
when inspecting with chrome i see this error:
```
file:///android_asset/www/resources/device-titlebar.jpg Failed to load resource: net::ERR_FILE_NOT_FOUND
```

i cannot find any `android_asset` folder being created.

**Comment by unimonkiez** [comment]
You should require your assets, so they will be copied to your bundle (either copied or transformed to base64 to skip the request).

```jsx
import deviceTitlebarImageUrl from 'src/resources/device-titlebar.png';

export default props => (
  <div>
    <img style={titlebarImage} src={deviceTitlebarImageUrl} />
  </div>
);
```

**Comment by iliran11** [comment]
thanks for the answer. it was helpful.
