### ISSUE TITLE
Unable to add platforms in cordova

### ISSUE THREAD

**Issue by kcrao** [unimonkiez/react-cordova-boilerplate#3]
Hi,  I'm trying to use this npm package and I can't add packages using "cordova platform add <platform>"
I have included the error message I receive below. Thanks for your package and any help you can provide

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:cordova"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-cordova-boilerplate@1.0.2 build:cordova: `webpack -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-cordova-boilerplate@1.0.2 build:cordova script 'webpack -c'.
npm ERR! This is most likely a problem with the react-cordova-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -c
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-cordova-boilerplate
npm ERR! There is likely additional logging output above.

**Comment by unimonkiez** [comment]
Hey,
First of all, thanks for the issue.
You did  run `npm install` before anything, right?

**Comment by brainlid** [comment]
I had no problem adding the platform "browser" and running "cordova run browser". If there isn't any further information from the reporter I would assume it is a configuration problem on their end.

**Comment by unimonkiez** [comment]
Tried it too last night, got to send me more relevant error log.
