### ISSUE TITLE
How to import non CommonJS JavaScript? 

### ISSUE THREAD

**Issue by sam3k** [unimonkiez/react-cordova-boilerplate#30]
I need to include a non CommonJS third party library which I am able to include by dropping the file in the root of the project; and then adding `<script src="someGlobalLogic.min.js"></script>` in src/index.ejs. 

This works on the browser but when compiling and previewing in Android, the following error occurs:

> HTML Webpack Plugin > Reference Error: someThirdPartyVar is not defined

Any suggestions?

**Comment by unimonkiez** [comment]
Can you tell me which third party did you try to include?

**Comment by sam3k** [comment]
For now [jDrupal](https://github.com/signalpoint/jDrupal) but who knows; maybe something else in the future?

**Comment by unimonkiez** [comment]
Seems like webpack was trying to run the code you inserted to your EJS file, though it should be running only in build time.  
I see there is an npm dependency for drupal [here](https://www.npmjs.com/package/drupal-client), but you can always use cdn and import it in your index.ejs file..

Can you post your EJS file?

**Comment by sam3k** [comment]
Hey @unimonkiez, sorry for the delay. This is what I tried:

on src/index.ejs:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>TodoMVC app</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="jdrupal.min.js"></script>
  <% if(__PROD__) { %><script src="cordova.js"></script><% } %>
</head>
<body>
  <div id="app">
    <%= htmlWebpackPlugin.options.getAppContent() %>
  </div>
</body>
</html>
```

And for that to work on my browser locally, i had to drop the jdrupal.min.js in the root of the app:
```
LICENSE
src
jdrupal.min.js
README.md
node_modules
test
bin
npm-packages-offline-cache
www
config.xml
package.json
yarn.lock
hooks
platforms
plugins
```

Regarding drupal-client; this looks like a very nice solution. Will try this. Still, I want to make sure there is a way in this project to import non-commonJs packages as I can see this being sometimes necessary to include things like tracking scripts, etc.

**Comment by sam3k** [comment]
It seems related to this issue: https://github.com/jantimon/html-webpack-plugin/issues/212 

Basically, excluding the HTML file in the loaders. I tried it and the error does go away; but it now I get: "TypeError: $export is not a function" which is mentioned here: https://github.com/jantimon/html-webpack-plugin/issues/585

I will continue debugging but any pointers are greatly appreciated!
