### ISSUE TITLE
react-hot-loader is deprecated

### ISSUE THREAD

**Issue by brainlid** [unimonkiez/react-cordova-boilerplate#6]
The package.json is using [react-hot-loader](https://github.com/gaearon/react-hot-loader). However this has been deprecated (Sept 27 - 3months ago) and points to [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate) as an example of how to replace it.

Admittedly I'm too new to webpack hot loading to put it all together for a cordova example for myself.

**Comment by unimonkiez** [comment]
I was thinking on updating to babel 6, will update react-HMR once Dan will support babel 6

**Comment by unimonkiez** [comment]
Now there is support for babel 6 :)

**Comment by unimonkiez** [comment]
Fixed and actually builds faster :)
